### ISSUE TITLE
docs/EntityManagerDbusAPI.md out of date

### ISSUE THREAD

**Issue by hyvedesignsolutions** [openbmc/entity-manager#4]
Is this docs/EntityManagerDbusAPI.md out of date ?
I don't see it has correct reference to dbus-interface as described here [https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory/Item](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory/Item)

**Comment by edtanous** [comment]
It's possible it is, patches to update it are welcome, but I can't tell from your request what specifically is out of date about it.  Can you be more specific?

**Comment by edtanous** [comment]
Closing from lack of response from submitter.  For anything "out of date" feel free to directly open patches to resolve issues with the documentation.  That is generally faster than filing issues.
