### ISSUE TITLE
Help for getting all the FRU's D-bus object paths dynamically .

### ISSUE THREAD

**Issue by edineshkumar** [openbmc/entity-manager#5]
D-bus service and object paths is given below,

![image](https://user-images.githubusercontent.com/41941042/88213781-d467c880-cc76-11ea-8d7a-337f145b441a.png)

Assume few extra object paths also will be present, like
+-/xyz/openbmc_project/FruDevice/F1UL16RISER3
+-/xyz/openbmc_project/FruDevice/FFPANEL
+-/xyz/openbmc_project/FruDevice/S_1100ADU00_201

How I can get all the object paths dynamically ?

For that "**GetObject** " method is required ?
"**GetObject**" method  is not there in fru device. How to add this method?
![image](https://user-images.githubusercontent.com/41941042/88215042-b69b6300-cc78-11ea-9cd1-e0bd7f64dddb.png)

There is any possibility to get all the object paths under /xyz/openbmc_project/FruDevice  except "**GetObject**" method ?

**Comment by feistjj** [comment]
> How I can get all the object paths dynamically

Call GetSubtree or GetSubtree paths from the mapper

> There is any possibility to get all the object paths

If you want all the data there is an object manager at the root that you can call get managed objects

**Comment by edineshkumar** [comment]
@feistjj ,
I can able to get all the object paths with help of GetSubtree. 
Thank you so much.

Device ID (**"FRU Device Description : Builtin FRU Device (ID 0)"**) is not present in Fru's D-bus property list. Do you have any concern for that?

**Comment by feistjj** [comment]
That is set by the baseboard fru which can either be placed at /etc/fru/baseboard.fru.bin (if no onboard eeprom), or if it has the correct chassis type intel-ipmi-oem will set it to ID 0 https://github.com/openbmc/intel-ipmi-oem/blob/9a13daaefbf2da4bcecca625b2f4b09fc9fb77f0/src/storagecommands.cpp#L199

**Comment by edineshkumar** [comment]
Thanks for your information.

Closing the issue.
