### ISSUE TITLE
Cannot tree EntityManager dbus service

### ISSUE THREAD

**Issue by boyercee** [openbmc/entity-manager#7]
I have a working configuration of Entity Manager to detect a board using the FruDevice probe of its EEPROM, so Entity Manager creates the dbus inventory for the exposed FRU fields. I can tree EntityManager dbus service with these versions of openbmc and entity-manager repos,

> openbmc SRCREV=708f0cc808588b2b08fcfce91271b2b5e9c9f827
> entity-manager SRCREV=98063a4081498ef1840fb58c29e9134183f7d967

However, if I keep the configuration the same, but upgrade to a newer openbmc repo using a later entity-manager revision,

> openbmc SRCREV=3f877c75b73e6d18a12f1ce2179b358fe7f92f36
> entity-manager SRCREV=c76af0fb1defcc9cc3d000c1ca7592d0f01df2a1

Then a tree of xyz.openbmc_project.EntityManager will either not show the inventory, or it will fail to show any objects. FruDevice is still publishing EEPROM FRU to dbus for Entity Manager to probe.

Not showing inventory objects:

![image](https://user-images.githubusercontent.com/62068216/102522975-8f489680-405c-11eb-936c-c40a7aa18f28.png)

Fails to show any objects:

![image](https://user-images.githubusercontent.com/62068216/102523038-a5565700-405c-11eb-8731-d2683d75cf29.png)

I realize that there are months of difference between the SRCREVs, and I am tracing the revisions to see what may cause the issue. Please help me determine the cause and the necessary changes to make.

**Comment by edtanous** [comment]
I suspect this was resolved on master a while back with encoding changes.  If this is still an issue, feel free to reopen.
